 export const entityOptions = [
    { value: 'gtbank', label: 'GTBank' },
    { value: 'access-bank', label: 'Access Bank' },
    { value: 'zenith-bank', label: 'Zenith Bank' },
    { value: 'first-bank', label: 'First Bank' },
    { value: 'uba', label: 'UBA' },
    { value: 'fidelity-bank', label: 'Fidelity Bank' },
  ];

  export const managerOptions = [
    { value: 'john-doe', label: 'John Doe' },
    { value: 'jane-smith', label: 'Jane Smith' },
    { value: 'michael-johnson', label: 'Michael Johnson' },
    { value: 'sarah-williams', label: 'Sarah Williams' },
    { value: 'david-brown', label: 'David Brown' },
    { value: 'emily-jones', label: 'Emily Jones' },
    { value: 'chris-davis', label: 'Chris Davis' },
    { value: 'lisa-miller', label: 'Lisa Miller' },
    { value: 'kevin-wilson', label: 'Kevin Wilson' },
    { value: 'amanda-moore', label: 'Amanda Moore' },
  ];


 export const teams = [
  { name: 'IT Support', code: 'ADM', desc: 'Manages system settings, user roles, and platform configurations', email: 'admin@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Henry Omofonmwan', created: '24/01/2024', status: 'Active' },
  { name: 'Change Management Team', code: 'ADD', desc: 'Handles all change requests and implementations across systems', email: 'change@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Sarah Williams', created: '15/02/2024', status: 'Active' },
  { name: 'Incident Manager', code: 'GGA', desc: 'Responds to and resolves system incidents and outages', email: 'incident@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'John Davidson', created: '10/03/2024', status: 'Deactivated' },
  { name: 'Service Request Manager', code: 'SRM', desc: 'Manages service requests and fulfillment processes', email: 'service@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Mary Johnson', created: '05/04/2024', status: 'Active' },
  { name: 'Problem Manager', code: 'PRM', desc: 'Identifies and resolves root causes of problems and issues', email: 'problem@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'David Brown', created: '20/04/2024', status: 'Active' },
  { name: 'Network Operations', code: 'NET', desc: 'Manages and maintains network infrastructure and connectivity', email: 'network@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Michael Adebayo', created: '12/01/2024', status: 'Active' },
  { name: 'Database Administration', code: 'DBA', desc: 'Handles database management, optimization and maintenance', email: 'dba@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Jennifer Okoro', created: '18/02/2024', status: 'Active' },
  { name: 'Security Operations', code: 'SEC', desc: 'Monitors and responds to security threats and vulnerabilities', email: 'security@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'James Okafor', created: '22/03/2024', status: 'Active' },
  { name: 'Application Support', code: 'APS', desc: 'Provides support for business applications and software', email: 'apps@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Grace Chukwu', created: '08/04/2024', status: 'Active' },
  { name: 'Infrastructure Team', code: 'INF', desc: 'Manages server infrastructure and data center operations', email: 'infrastructure@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Robert Adeyemi', created: '14/05/2024', status: 'Active' },
  { name: 'Cloud Services', code: 'CLD', desc: 'Manages cloud infrastructure and cloud-based services', email: 'cloud@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Patricia Nwosu', created: '29/06/2024', status: 'Active' },
  { name: 'Backup and Recovery', code: 'BKP', desc: 'Handles data backup, restoration and disaster recovery', email: 'backup@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Daniel Ibrahim', created: '03/07/2024', status: 'Active' },
  { name: 'Monitoring Team', code: 'MON', desc: 'Monitors system performance and alerts for issues', email: 'monitoring@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Susan Musa', created: '11/08/2024', status: 'Active' },
  { name: 'Desktop Support', code: 'DES', desc: 'Provides end-user desktop and laptop support', email: 'desktop@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Kevin Eze', created: '19/09/2024', status: 'Active' },
  { name: 'Mobile Banking Support', code: 'MOB', desc: 'Supports mobile banking applications and services', email: 'mobile@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Amanda Bello', created: '25/10/2024', status: 'Active' },
  { name: 'Internet Banking', code: 'IBK', desc: 'Manages online banking platform and services', email: 'internetbanking@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Paul Oni', created: '07/11/2024', status: 'Active' },
  { name: 'ATM Support', code: 'ATM', desc: 'Maintains and supports ATM network operations', email: 'atm@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Ruth Adeleke', created: '15/12/2024', status: 'Active' },
  { name: 'POS Support', code: 'POS', desc: 'Supports point-of-sale terminal operations', email: 'pos@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Samuel Ojo', created: '22/01/2024', status: 'Active' },
  { name: 'Card Services', code: 'CRD', desc: 'Manages debit and credit card operations', email: 'cards@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Elizabeth Sani', created: '30/02/2024', status: 'Active' },
  { name: 'Payment Operations', code: 'PAY', desc: 'Handles payment processing and transactions', email: 'payments@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Thomas Yakubu', created: '08/03/2024', status: 'Active' },
  { name: 'Settlement Team', code: 'SET', desc: 'Manages transaction settlement and reconciliation', email: 'settlement@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Margaret Okon', created: '16/04/2024', status: 'Active' },
  { name: 'Reconciliation', code: 'REC', desc: 'Performs account reconciliation and balancing', email: 'reconciliation@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Andrew Bala', created: '24/05/2024', status: 'Active' },
  { name: 'Trade Finance', code: 'TRD', desc: 'Supports trade finance operations and services', email: 'tradefinance@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Cynthia Nwachukwu', created: '02/06/2024', status: 'Active' },
  { name: 'Corporate Banking', code: 'COR', desc: 'Supports corporate banking services and clients', email: 'corporate@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Peter Adekunle', created: '10/07/2024', status: 'Active' },
  { name: 'Retail Banking', code: 'RET', desc: 'Manages retail banking operations and services', email: 'retail@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Blessing Okafor', created: '18/08/2024', status: 'Active' },
  { name: 'Wealth Management', code: 'WLT', desc: 'Supports wealth management and private banking', email: 'wealth@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Jonathan Eze', created: '26/09/2024', status: 'Active' },
  { name: 'Investment Banking', code: 'INV', desc: 'Handles investment banking operations', email: 'investment@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Victoria Sule', created: '04/10/2024', status: 'Active' },
  { name: 'Treasury Operations', code: 'TRS', desc: 'Manages treasury and cash management services', email: 'treasury@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Benjamin Chinedu', created: '12/11/2024', status: 'Active' },
  { name: 'Risk Management', code: 'RSK', desc: 'Identifies and manages operational risks', email: 'risk@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Dorothy Mohammed', created: '20/12/2024', status: 'Active' },
  { name: 'Compliance Team', code: 'CMP', desc: 'Ensures regulatory compliance and monitoring', email: 'compliance@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Franklin Osei', created: '28/01/2024', status: 'Active' },
  { name: 'Audit Team', code: 'AUD', desc: 'Performs internal audits and controls review', email: 'audit@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Irene Nwankwo', created: '05/02/2024', status: 'Active' },
  { name: 'Legal Support', code: 'LEG', desc: 'Provides legal and contractual support', email: 'legal@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'George Abubakar', created: '13/03/2024', status: 'Active' },
  { name: 'HR Systems', code: 'HRS', desc: 'Manages HR systems and employee data', email: 'hrsystems@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Hannah Okeke', created: '21/04/2024', status: 'Active' },
  { name: 'Payroll Support', code: 'PYR', desc: 'Supports payroll processing and systems', email: 'payroll@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Isaac Adebisi', created: '29/05/2024', status: 'Active' },
  { name: 'Finance Systems', code: 'FIN', desc: 'Manages financial systems and accounting software', email: 'finance@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Joyce Aliu', created: '06/06/2024', status: 'Active' },
  { name: 'Procurement', code: 'PRO', desc: 'Handles procurement and vendor management systems', email: 'procurement@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Lawrence Ogun', created: '14/07/2024', status: 'Active' },
  { name: 'Facilities IT', code: 'FAC', desc: 'Supports IT systems for facilities management', email: 'facilities@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Monica Danjuma', created: '22/08/2024', status: 'Active' },
  { name: 'Business Intelligence', code: 'BIZ', desc: 'Manages BI tools and data analytics platforms', email: 'bi@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Nathaniel Ade', created: '30/09/2024', status: 'Active' },
  { name: 'Data Warehouse', code: 'DWH', desc: 'Maintains data warehouse and ETL processes', email: 'datawarehouse@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Olivia Bamigboye', created: '08/10/2024', status: 'Active' },
  { name: 'Reporting Team', code: 'RPT', desc: 'Generates and distributes business reports', email: 'reporting@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Philip Idris', created: '16/11/2024', status: 'Active' },
  { name: 'CRM Support', code: 'CRM', desc: 'Supports customer relationship management system', email: 'crm@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Queeneth Ola', created: '24/12/2024', status: 'Active' },
  { name: 'Marketing Systems', code: 'MKT', desc: 'Manages marketing automation and campaign systems', email: 'marketing@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Raymond Nwosu', created: '01/01/2024', status: 'Active' },
  { name: 'Digital Channels', code: 'DIG', desc: 'Supports digital banking channels and platforms', email: 'digital@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Stella Adeyinka', created: '09/02/2024', status: 'Active' },
  { name: 'API Management', code: 'API', desc: 'Manages API gateway and integrations', email: 'api@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Theodore Okafor', created: '17/03/2024', status: 'Active' },
  { name: 'Integration Team', code: 'INT', desc: 'Handles system integrations and interfaces', email: 'integration@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Uchechi Nnamdi', created: '25/04/2024', status: 'Active' },
  { name: 'Middleware Support', code: 'MID', desc: 'Supports middleware and messaging systems', email: 'middleware@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Vincent Sani', created: '03/05/2024', status: 'Active' },
  { name: 'Development Team', code: 'DEV', desc: 'Software development and customization team', email: 'development@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Wendy Okoro', created: '11/06/2024', status: 'Active' },
  { name: 'QA Team', code: 'QAT', desc: 'Quality assurance and testing team', email: 'qa@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Xavier Balogun', created: '19/07/2024', status: 'Active' },
  { name: 'Release Management', code: 'RLS', desc: 'Manages software releases and deployments', email: 'release@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Yvonne Musa', created: '27/08/2024', status: 'Active' },
  { name: 'Project Management', code: 'PJM', desc: 'IT project management and coordination', email: 'projects@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Zainab Adebayo', created: '04/09/2024', status: 'Active' },
  { name: 'Business Analysis', code: 'BAN', desc: 'Business analysis and requirements gathering', email: 'businessanalysis@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Abdul Johnson', created: '12/10/2024', status: 'Active' },
  { name: 'Training Team', code: 'TRN', desc: 'IT training and user education', email: 'training@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Bose Ogunleye', created: '20/11/2024', status: 'Active' },
  { name: 'Documentation', code: 'DOC', desc: 'Technical documentation and knowledge management', email: 'documentation@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Chidi Okonkwo', created: '28/12/2024', status: 'Active' },
  { name: 'Service Desk', code: 'SVD', desc: 'First-line support and service desk operations', email: 'servicedesk@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Damilola Yusuf', created: '05/01/2024', status: 'Active' },
  { name: 'Help Desk', code: 'HLP', desc: 'User help desk and technical assistance', email: 'helpdesk@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Emeka Nwosu', created: '13/02/2024', status: 'Active' },
  { name: 'VIP Support', code: 'VIP', desc: 'Executive and VIP user support', email: 'vip@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Fatima Adeleke', created: '21/03/2024', status: 'Active' },
  { name: 'Branch IT Support', code: 'BRN', desc: 'Supports branch IT systems and equipment', email: 'branchit@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Gabriel Okafor', created: '29/04/2024', status: 'Active' },
  { name: 'Regional Support', code: 'REG', desc: 'Regional IT support and coordination', email: 'regional@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Halima Sani', created: '07/05/2024', status: 'Active' },
  { name: 'International Support', code: 'INT', desc: 'Supports international operations and branches', email: 'international@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Ibrahim Chukwu', created: '15/06/2024', status: 'Active' },
  { name: 'Vendor Management', code: 'VND', desc: 'Manages vendor relationships and performance', email: 'vendors@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Jumoke Adeyemi', created: '23/07/2024', status: 'Active' },
  { name: 'Contract Management', code: 'CNT', desc: 'IT contract management and administration', email: 'contracts@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Kolawole Bello', created: '31/08/2024', status: 'Active' },
  { name: 'License Management', code: 'LIC', desc: 'Software license management and compliance', email: 'licenses@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Lola Oni', created: '08/09/2024', status: 'Active' },
  { name: 'Asset Management', code: 'AST', desc: 'IT asset management and tracking', email: 'assets@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Musa Ibrahim', created: '16/10/2024', status: 'Active' },
  { name: 'Inventory Control', code: 'INV', desc: 'IT inventory control and management', email: 'inventory@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Ngozi Ojo', created: '24/11/2024', status: 'Active' },
  { name: 'Capacity Planning', code: 'CAP', desc: 'IT capacity planning and resource management', email: 'capacity@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Oluwatobi Yakubu', created: '02/12/2024', status: 'Active' },
  { name: 'Performance Team', code: 'PER', desc: 'System performance monitoring and optimization', email: 'performance@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Peace Okon', created: '10/01/2024', status: 'Active' },
  { name: 'Tuning Team', code: 'TUN', desc: 'Database and system performance tuning', email: 'tuning@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Quadri Bala', created: '18/02/2024', status: 'Active' },
  { name: 'Automation Team', code: 'AUT', desc: 'IT process automation and scripting', email: 'automation@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Rita Nwachukwu', created: '26/03/2024', status: 'Active' },
  { name: 'Scripting Team', code: 'SCR', desc: 'PowerShell and automation scripting', email: 'scripting@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Solomon Adekunle', created: '04/04/2024', status: 'Active' },
  { name: 'Monitoring Tools', code: 'MNT', desc: 'Monitoring tools administration and configuration', email: 'monitoringtools@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Temitope Okafor', created: '12/05/2024', status: 'Active' },
  { name: 'Alert Management', code: 'ALT', desc: 'Alert management and notification systems', email: 'alerts@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Umar Eze', created: '20/06/2024', status: 'Active' },
  { name: 'Backup Monitoring', code: 'BKM', desc: 'Backup job monitoring and verification', email: 'backupmon@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Veronica Sule', created: '28/07/2024', status: 'Active' },
  { name: 'DR Testing', code: 'DRT', desc: 'Disaster recovery testing and validation', email: 'dr@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Williams Chinedu', created: '05/08/2024', status: 'Active' },
  { name: 'BCP Team', code: 'BCP', desc: 'Business continuity planning and execution', email: 'bcp@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Xena Mohammed', created: '13/09/2024', status: 'Active' },
  { name: 'Crisis Management', code: 'CRM', desc: 'Crisis management and emergency response', email: 'crisis@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Yakubu Osei', created: '21/10/2024', status: 'Active' },
  { name: 'Emergency Support', code: 'EMS', desc: 'Emergency IT support and response', email: 'emergency@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Zara Nwankwo', created: '29/11/2024', status: 'Active' },
  { name: 'Weekend Support', code: 'WKD', desc: 'Weekend and after-hours support team', email: 'weekend@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Aaron Abubakar', created: '07/12/2024', status: 'Active' },
  { name: 'Holiday Support', code: 'HLD', desc: 'Holiday and special day support coverage', email: 'holiday@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Bella Okeke', created: '15/01/2024', status: 'Active' },
  { name: '24/7 Operations', code: 'OPS', desc: '24/7 operations center and support', email: 'operations@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Caleb Adebisi', created: '23/02/2024', status: 'Active' },
  { name: 'NOC Team', code: 'NOC', desc: 'Network Operations Center monitoring team', email: 'noc@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Diana Aliu', created: '03/03/2024', status: 'Active' },
  { name: 'SOC Team', code: 'SOC', desc: 'Security Operations Center monitoring team', email: 'soc@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Ethan Ogun', created: '11/04/2024', status: 'Active' },
  { name: 'Threat Intelligence', code: 'THR', desc: 'Threat intelligence and analysis', email: 'threat@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Faith Danjuma', created: '19/05/2024', status: 'Active' },
  { name: 'Vulnerability Management', code: 'VUL', desc: 'Vulnerability assessment and management', email: 'vulnerability@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Gideon Ade', created: '27/06/2024', status: 'Active' },
  { name: 'Penetration Testing', code: 'PEN', desc: 'Penetration testing and security assessment', email: 'pentest@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Hope Bamigboye', created: '05/07/2024', status: 'Active' },
  { name: 'Security Awareness', code: 'SAW', desc: 'Security awareness and training programs', email: 'securityaware@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Isaac Idris', created: '13/08/2024', status: 'Active' },
  { name: 'Access Control', code: 'ACC', desc: 'User access control and privilege management', email: 'accesscontrol@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Jasmine Ola', created: '21/09/2024', status: 'Active' },
  { name: 'Identity Management', code: 'IDM', desc: 'Identity and access management systems', email: 'identity@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Kingsley Nwosu', created: '29/10/2024', status: 'Active' },
  { name: 'Directory Services', code: 'DIR', desc: 'Active Directory and directory services', email: 'directory@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Lily Adeyinka', created: '06/11/2024', status: 'Active' },
  { name: 'Authentication Team', code: 'AUTH', desc: 'Authentication systems and multi-factor auth', email: 'auth@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Moses Okafor', created: '14/12/2024', status: 'Active' },
  { name: 'Encryption Team', code: 'ENC', desc: 'Encryption and data protection services', email: 'encryption@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Nadia Nnamdi', created: '22/01/2024', status: 'Active' },
  { name: 'PKI Team', code: 'PKI', desc: 'Public Key Infrastructure management', email: 'pki@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Oscar Sani', created: '30/02/2024', status: 'Active' },
  { name: 'Certificate Team', code: 'CRT', desc: 'Digital certificate management and renewal', email: 'certificates@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Penelope Okoro', created: '08/03/2024', status: 'Active' },
  { name: 'SSL Team', code: 'SSL', desc: 'SSL certificate management and configuration', email: 'ssl@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Quincy Balogun', created: '16/04/2024', status: 'Active' },
  { name: 'Firewall Team', code: 'FWL', desc: 'Firewall management and rule administration', email: 'firewall@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Rachel Musa', created: '24/05/2024', status: 'Active' },
  { name: 'Proxy Team', code: 'PRX', desc: 'Web proxy and content filtering management', email: 'proxy@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Samuel Adebayo', created: '02/06/2024', status: 'Active' },
  { name: 'VPN Team', code: 'VPN', desc: 'VPN access and remote connectivity', email: 'vpn@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Tina Johnson', created: '10/07/2024', status: 'Active' },
  { name: 'Remote Access', code: 'REM', desc: 'Remote access solutions and support', email: 'remote@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Uche Davidson', created: '18/08/2024', status: 'Active' },
  { name: 'Mobile Device Management', code: 'MDM', desc: 'Mobile device management and security', email: 'mdm@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Victor Williams', created: '26/09/2024', status: 'Active' },
  { name: 'Endpoint Protection', code: 'EPT', desc: 'Endpoint protection and antivirus management', email: 'endpoint@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Wanda Omofonmwan', created: '04/10/2024', status: 'Active' },
  { name: 'Patch Management', code: 'PCH', desc: 'Patch management and vulnerability remediation', email: 'patches@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Xander Brown', created: '12/11/2024', status: 'Active' },
  { name: 'Software Distribution', code: 'SFT', desc: 'Software distribution and deployment', email: 'software@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Yara Johnson', created: '20/12/2024', status: 'Active' },
  { name: 'Image Management', code: 'IMG', desc: 'OS image management and deployment', email: 'imaging@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Zane Davidson', created: '28/01/2024', status: 'Active' },
  { name: 'Configuration Management', code: 'CFG', desc: 'Configuration management and compliance', email: 'config@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Alice Williams', created: '05/02/2024', status: 'Active' },
  { name: 'CMDB Team', code: 'CMD', desc: 'Configuration Management Database team', email: 'cmdb@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Brian Brown', created: '13/03/2024', status: 'Active' },
  { name: 'Service Catalog', code: 'CAT', desc: 'Service catalog management and maintenance', email: 'catalog@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Catherine Johnson', created: '21/04/2024', status: 'Active' },
  { name: 'Knowledge Management', code: 'KNW', desc: 'Knowledge base and documentation management', email: 'knowledge@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'David Williams', created: '29/05/2024', status: 'Active' },
  { name: 'SLA Management', code: 'SLA', desc: 'Service Level Agreement monitoring and reporting', email: 'sla@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Eva Brown', created: '06/06/2024', status: 'Active' },
  { name: 'OLA Management', code: 'OLA', desc: 'Operational Level Agreement management', email: 'ola@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Frank Johnson', created: '14/07/2024', status: 'Active' },
  { name: 'KPI Reporting', code: 'KPI', desc: 'KPI monitoring and performance reporting', email: 'kpi@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Grace Williams', created: '22/08/2024', status: 'Active' },
  { name: 'Metrics Team', code: 'MET', desc: 'IT metrics collection and analysis', email: 'metrics@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Henry Brown', created: '30/09/2024', status: 'Active' },
  { name: 'Dashboard Team', code: 'DSH', desc: 'Dashboard development and maintenance', email: 'dashboard@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Irene Johnson', created: '08/10/2024', status: 'Active' },
  { name: 'Visualization Team', code: 'VIZ', desc: 'Data visualization and reporting', email: 'visualization@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Jack Williams', created: '16/11/2024', status: 'Active' },
  { name: 'Analytics Team', code: 'ANA', desc: 'Data analytics and insights generation', email: 'analytics@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Karen Brown', created: '24/12/2024', status: 'Active' },
  { name: 'Machine Learning', code: 'MLT', desc: 'Machine learning and AI initiatives', email: 'ml@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Leo Johnson', created: '01/01/2024', status: 'Active' },
  { name: 'AI Team', code: 'AIT', desc: 'Artificial intelligence solutions team', email: 'ai@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Mia Williams', created: '09/02/2024', status: 'Active' },
  { name: 'RPA Team', code: 'RPA', desc: 'Robotic Process Automation development', email: 'rpa@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Noah Brown', created: '17/03/2024', status: 'Active' },
  { name: 'Blockchain Team', code: 'BLC', desc: 'Blockchain technology and solutions', email: 'blockchain@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Olivia Johnson', created: '25/04/2024', status: 'Active' },
  { name: 'Digital Innovation', code: 'DIN', desc: 'Digital innovation and emerging technologies', email: 'innovation@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Paul Williams', created: '03/05/2024', status: 'Active' },
  { name: 'Research and Development', code: 'RND', desc: 'Technology research and development', email: 'randd@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Quinn Brown', created: '11/06/2024', status: 'Active' },
  { name: 'Prototype Team', code: 'PRO', desc: 'Prototype development and testing', email: 'prototype@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Ryan Johnson', created: '19/07/2024', status: 'Active' },
  { name: 'POC Team', code: 'POC', desc: 'Proof of Concept development and validation', email: 'poc@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Sofia Williams', created: '27/08/2024', status: 'Active' },
  { name: 'Innovation Lab', code: 'INL', desc: 'Innovation lab and experimentation', email: 'innovationlab@accessbankplc.com', entity: 'Access Bank Nigeria', manager: 'Thomas Brown', created: '04/09/2024', status: 'Active' },
 ]